export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  GAME_FULL: "GAME_FULL",
  UNAUTHORIZED: "UNAUTHORIZED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  INVALID_PHASE: "INVALID_PHASE",
  PHASE_NOT_COMPLETE: "PHASE_NOT_COMPLETE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

